from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="cross-dim-transfer",
    version="1.0.0",
    author="",
    author_email="",
    description="Cross-Dimensional Knowledge Transfer for Data-Efficient Medical Image Analysis",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/cross-dim-transfer",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scipy>=1.10.0",
        "scikit-learn>=1.3.0",
        "Pillow>=9.5.0",
        "pydicom>=2.4.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "transformers>=4.35.0",
        "bitsandbytes>=0.41.0",
        "accelerate>=0.25.0",
        "umap-learn>=0.5.3",
        "tqdm>=4.66.0",
        "pyyaml>=6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "black>=23.9.0",
            "flake8>=6.1.0",
            "isort>=5.12.0",
            "mypy>=1.6.0",
            "jupyter>=1.0.0",
        ],
        "tensorboard": [
            "tensorboard>=2.14.0",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
    ],
    keywords=[
        "medical-imaging",
        "few-shot-learning",
        "cross-modal",
        "knowledge-transfer",
        "deep-learning",
        "pathology",
        "ct-scan",
        "cancer-classification",
        "haidef",
        "medgemma",
    ],
    project_urls={
        "Bug Reports": "https://github.com/yourusername/cross-dim-transfer/issues",
        "Source": "https://github.com/yourusername/cross-dim-transfer",
        "Documentation": "https://github.com/yourusername/cross-dim-transfer/tree/main/docs",
    },
)
